### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by sverhoeven** [iomega/spec2vec#40]
Does the library support Python 3.9? If so please add classifier in setup.py and run 3.9 on CI matrix.

**Comment by florian-huber** [comment]
Good point! I was also thinking of it yesterday when I found something like ``python>=3.7`` somewhere in the code.
Which CI runs do we have to include in you opinion?
The pip runs are fast so that can be included, but do we have to run the Anaconda verify for all (3x3 cases), or can we skip some cases in the CI?

**Comment by florian-huber** [comment]
Started adding 3.9 to PR #39 .

**Comment by florian-huber** [comment]
OK, that gave failling tests. So I will not add it as part of PR #39 but we should handle that in a separate PR.

**Comment by sverhoeven** [comment]
The Conda package is pinned to `python >=3.7,<3.9` and is noarch so having a matrix for anaconda_build does not make sense to me. As during publish job only the build artifact of py37+ubuntu-latest is published so why should we do more combinations for each push.

Having the full matrix for anaconda_verify is useful because the conda package can be installed with all those combis.

**Comment by florian-huber** [comment]
Fixed with #68
