### ISSUE TITLE
Make spec2vec compatible with gensim4.0.0

### ISSUE THREAD

**Issue by niekdejonge** [iomega/spec2vec#61]
A new version of gensim4.0.0 is available, that is not fully compatible with spec2vec. 
When running spec2vec (from ms2query) the following error occurs:
"The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead."

For more details see https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

Changes should be made so spec2vec is compatible with gensim again or an older version of gensim should be used in setup.py.

**Comment by benbowen** [comment]
@niekdejonge Which version of gensim are you using that is working?  I am facing the same problem.  I'll pin at 3.0 and see how it goes.

**Comment by benbowen** [comment]
Setting version in conda yml like this got it working for me
  - gensim<4.0.0
  - spec2vec=0.4.0

**Comment by niekdejonge** [comment]
@benbowen, setting the version of gensim to <4.0.0 is a solution for now indeed. 
A new version of Spec2Vec will soon be released to make it compatible with gensim 4.0.0 as well. 
Sorry for the inconvenience.

**Comment by florian-huber** [comment]
The next release of Spec2Vec (0.5.0) will run on gensim>=4.0.0. 
The Spec2Vec code should run as before, but some scripts that use gensim commands or parameters might run into some issues since the gensim API changed a bit. If this indeed happens, please also check the [gensim information on how to migrate](https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4).
